//! The command catalog — what `COMMAND`, `COMMAND INFO`, `COMMAND COUNT`,
//! `COMMAND LIST` and `COMMAND DOCS` report.
//!
//! Arity, flags and key positions are transcribed from a real `redis-server`
//! 7.2.5's own `COMMAND INFO`, not written from memory. Clients and proxies
//! route on those numbers — a wrong `first_key` sends a command to the wrong
//! shard, and a wrong arity makes a client reject a call the server would have
//! accepted — so the reference implementation is the only honest source. The
//! commands Recached invents have no Redis entry and are declared here
//! directly.
//!
//! Summaries come from `docs/server/commands.md`, so the text a client sees is
//! the text that was reviewed and published rather than a second description
//! that can drift away from it.

/// One row of the catalog. Mirrors the fields `COMMAND INFO` returns, in order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CommandSpec {
    /// Lowercase, as Redis reports it.
    pub name: &'static str,
    /// Total argument count including the command name. Negative means "at
    /// least this many", the Redis convention.
    pub arity: i32,
    pub flags: &'static [&'static str],
    /// 1-based position of the first key argument, or 0 for keyless commands.
    pub first_key: i32,
    /// Position of the last key argument; -1 means "to the end".
    pub last_key: i32,
    /// Stride between key positions.
    pub step: i32,
    /// Section of the command reference this belongs to.
    pub group: &'static str,
    /// One-line description, for `COMMAND DOCS`.
    pub summary: &'static str,
}

#[allow(clippy::too_many_arguments)]
const fn spec(
    name: &'static str,
    arity: i32,
    flags: &'static [&'static str],
    first_key: i32,
    last_key: i32,
    step: i32,
    group: &'static str,
    summary: &'static str,
) -> CommandSpec {
    CommandSpec {
        name,
        arity,
        flags,
        first_key,
        last_key,
        step,
        group,
        summary,
    }
}

/// Every command Recached accepts. Kept in sync with the parser by
/// `catalog_covers_every_command` in this module and by
/// `every_command_is_in_the_catalog` in the server.
pub const CATALOG: &[CommandSpec] = &[
    // ── Transcribed from redis-server 7.2.5 ───────────────────────────────
    spec(
        "append",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Appends a string to the end of the existing value.",
    ),
    spec(
        "auth",
        -2,
        &[
            "noscript",
            "loading",
            "stale",
            "fast",
            "no_auth",
            "allow_busy",
        ],
        0,
        0,
        0,
        "core",
        "Authenticates the connection.",
    ),
    spec(
        "bgsave",
        -1,
        &["admin", "noscript", "no_async_loading"],
        0,
        0,
        0,
        "persistence",
        "Triggers a background snapshot.",
    ),
    spec(
        "dbsize",
        1,
        &["readonly", "fast"],
        0,
        0,
        0,
        "keys",
        "Returns the total number of keys in the store.",
    ),
    spec(
        "decr",
        2,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Decrements the integer value of a key by 1.",
    ),
    spec(
        "decrby",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Decrements the integer value of a key by the given integer.",
    ),
    spec(
        "del",
        -2,
        &["write"],
        1,
        -1,
        1,
        "keys",
        "Deletes one or more keys.",
    ),
    spec(
        "discard",
        1,
        &["noscript", "loading", "stale", "fast", "allow_busy"],
        0,
        0,
        0,
        "transactions",
        "Abandons the transaction queue.",
    ),
    spec(
        "exec",
        1,
        &["noscript", "loading", "stale", "skip_slowlog"],
        0,
        0,
        0,
        "transactions",
        "Executes all queued commands.",
    ),
    spec(
        "exists",
        -2,
        &["readonly", "fast"],
        1,
        -1,
        1,
        "keys",
        "Returns the number of keys that exist among the provided arguments.",
    ),
    spec(
        "expire",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "expiry",
        "Set a timeout on a key in seconds.",
    ),
    spec(
        "expireat",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "expiry",
        "Set an absolute expiry time as a Unix timestamp (seconds).",
    ),
    spec(
        "flushdb",
        -1,
        &["write"],
        0,
        0,
        0,
        "keys",
        "Removes all keys from the store.",
    ),
    spec(
        "get",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "strings",
        "Returns the value of a key, or nil if the key does not exist or has expired.",
    ),
    spec(
        "getrange",
        4,
        &["readonly"],
        1,
        1,
        1,
        "strings",
        "Returns the inclusive byte range start..end of the string.",
    ),
    spec(
        "getset",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Sets the key to a new value and returns the old value atomically.",
    ),
    spec(
        "hdel",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "hash",
        "Deletes one or more fields from a hash.",
    ),
    spec(
        "hello",
        -1,
        &[
            "noscript",
            "loading",
            "stale",
            "fast",
            "no_auth",
            "allow_busy",
        ],
        0,
        0,
        0,
        "core",
        "Reports server info and negotiates the protocol version.",
    ),
    spec(
        "hexists",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "hash",
        "Returns 1 if the field exists in the hash, 0 otherwise.",
    ),
    spec(
        "hget",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "hash",
        "Returns the value of a specific field.",
    ),
    spec(
        "hgetall",
        2,
        &["readonly"],
        1,
        1,
        1,
        "hash",
        "Returns all field-value pairs of a hash as a flat array: field1, value1, field2, value2, ...",
    ),
    spec(
        "hincrby",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "hash",
        "Increments the integer value of a hash field by the given integer.",
    ),
    spec(
        "hincrbyfloat",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "hash",
        "Increments the float value of a hash field by the given float.",
    ),
    spec(
        "hkeys",
        2,
        &["readonly"],
        1,
        1,
        1,
        "hash",
        "Returns all field names in the hash.",
    ),
    spec(
        "hlen",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "hash",
        "Returns the number of fields in the hash.",
    ),
    spec(
        "hmget",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "hash",
        "Returns the values of multiple fields.",
    ),
    spec(
        "hmset",
        -4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "hash",
        "Deprecated alias of HSET, kept for older clients.",
    ),
    spec(
        "hscan",
        -3,
        &["readonly"],
        1,
        1,
        1,
        "hash",
        "Iterates a hash incrementally: returns the next cursor plus at most COUNT field-value pairs (default 10).",
    ),
    spec(
        "hset",
        -4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "hash",
        "Sets one or more fields in a hash.",
    ),
    spec(
        "hsetnx",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "hash",
        "Sets a field only if it does not already exist.",
    ),
    spec(
        "hvals",
        2,
        &["readonly"],
        1,
        1,
        1,
        "hash",
        "Returns all values in the hash.",
    ),
    spec(
        "incr",
        2,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Increments the integer value of a key by 1.",
    ),
    spec(
        "incrby",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Increments the integer value of a key by the given integer.",
    ),
    spec(
        "info",
        -1,
        &["loading", "stale"],
        0,
        0,
        0,
        "core",
        "Reports server statistics as a text blob, in Redis's # Section / field:value format.",
    ),
    spec(
        "keys",
        2,
        &["readonly"],
        0,
        0,
        0,
        "keys",
        "Returns all keys matching the glob pattern.",
    ),
    spec(
        "lastsave",
        1,
        &["loading", "stale", "fast"],
        0,
        0,
        0,
        "persistence",
        "Returns the Unix timestamp (seconds) of the most recent successful snapshot.",
    ),
    spec(
        "lindex",
        3,
        &["readonly"],
        1,
        1,
        1,
        "list",
        "Returns the element at the given index.",
    ),
    spec(
        "llen",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "list",
        "Returns the length of the list, or 0 if the key does not exist.",
    ),
    spec(
        "lpop",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "list",
        "Removes and returns the first element (or count elements) from the list.",
    ),
    spec(
        "lpush",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "list",
        "Prepends one or more elements to the head of a list.",
    ),
    spec(
        "lpushx",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "list",
        "Like LPUSH, but only if the key already exists.",
    ),
    spec(
        "lrange",
        4,
        &["readonly"],
        1,
        1,
        1,
        "list",
        "Returns the elements of the list between index start and stop (inclusive).",
    ),
    spec(
        "lrem",
        4,
        &["write"],
        1,
        1,
        1,
        "list",
        "Removes occurrences of element from the list.",
    ),
    spec(
        "lset",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "list",
        "Sets the list element at the given index to a new value.",
    ),
    spec(
        "ltrim",
        4,
        &["write"],
        1,
        1,
        1,
        "list",
        "Keeps only the elements between start and stop, removing the rest.",
    ),
    spec(
        "mget",
        -2,
        &["readonly", "fast"],
        1,
        -1,
        1,
        "strings",
        "Returns the values of multiple keys.",
    ),
    spec(
        "mset",
        -3,
        &["write", "denyoom"],
        1,
        -1,
        2,
        "strings",
        "Sets multiple keys to their respective values in a single atomic operation.",
    ),
    spec(
        "multi",
        1,
        &["noscript", "loading", "stale", "fast", "allow_busy"],
        0,
        0,
        0,
        "transactions",
        "Begins a transaction.",
    ),
    spec(
        "persist",
        2,
        &["write", "fast"],
        1,
        1,
        1,
        "expiry",
        "Removes the TTL from a key, making it persistent.",
    ),
    spec(
        "pexpire",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "expiry",
        "Set a timeout in milliseconds.",
    ),
    spec(
        "pexpireat",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "expiry",
        "Set an absolute expiry time as a Unix timestamp in milliseconds.",
    ),
    spec(
        "ping",
        -1,
        &["fast"],
        0,
        0,
        0,
        "core",
        "Returns PONG, or echoes message if provided.",
    ),
    spec(
        "psetex",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "strings",
        "Set a key with a millisecond-precision expiry.",
    ),
    spec(
        "psubscribe",
        -2,
        &["pubsub", "noscript", "loading", "stale"],
        0,
        0,
        0,
        "pub/sub",
        "Subscribes to channels matching a glob pattern.",
    ),
    spec(
        "pttl",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "expiry",
        "Returns the remaining TTL in milliseconds.",
    ),
    spec(
        "publish",
        3,
        &["pubsub", "loading", "stale", "fast"],
        0,
        0,
        0,
        "pub/sub",
        "Publishes a message to all subscribers of the given channel and all clients with matching pattern subscriptions.",
    ),
    spec(
        "punsubscribe",
        -1,
        &["pubsub", "noscript", "loading", "stale"],
        0,
        0,
        0,
        "pub/sub",
        "Unsubscribes from pattern subscriptions.",
    ),
    spec("rename", 3, &["write"], 1, 2, 1, "keys", "Renames a key."),
    spec(
        "replicaof",
        3,
        &["admin", "noscript", "stale", "no_async_loading"],
        0,
        0,
        0,
        "replication",
        "Promotes this replica to a primary: it stops following its upstream and begins accepting writes.",
    ),
    spec(
        "rpop",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "list",
        "Removes and returns the last element (or count elements) from the list.",
    ),
    spec(
        "rpush",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "list",
        "Appends one or more elements to the tail of a list.",
    ),
    spec(
        "rpushx",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "list",
        "Like RPUSH, but only if the key already exists.",
    ),
    spec(
        "sadd",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "set",
        "Adds one or more members to a set.",
    ),
    spec(
        "save",
        1,
        &["admin", "noscript", "no_async_loading", "no_multi"],
        0,
        0,
        0,
        "persistence",
        "Synchronously writes a snapshot to disk.",
    ),
    spec(
        "scan",
        -2,
        &["readonly"],
        0,
        0,
        0,
        "keys",
        "Iterates keys incrementally, returning at most COUNT keys per call (default 10) plus the next cursor.",
    ),
    spec(
        "scard",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "set",
        "Returns the number of members in the set.",
    ),
    spec(
        "sdiff",
        -2,
        &["readonly"],
        1,
        -1,
        1,
        "set",
        "Returns the members in the first set that are not in any of the other sets.",
    ),
    spec(
        "sdiffstore",
        -3,
        &["write", "denyoom"],
        1,
        -1,
        1,
        "set",
        "Stores the difference into destination and returns its size.",
    ),
    spec(
        "set",
        -3,
        &["write", "denyoom"],
        1,
        1,
        1,
        "strings",
        "Set a key to a string value.",
    ),
    spec(
        "setex",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "strings",
        "Set a key with an integer-second expiry.",
    ),
    spec(
        "setnx",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Set a key only if it does not exist.",
    ),
    spec(
        "sinter",
        -2,
        &["readonly"],
        1,
        -1,
        1,
        "set",
        "Returns the intersection of all given sets.",
    ),
    spec(
        "sinterstore",
        -3,
        &["write", "denyoom"],
        1,
        -1,
        1,
        "set",
        "Stores the intersection into destination and returns its size.",
    ),
    spec(
        "sismember",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "set",
        "Returns 1 if the member exists in the set, 0 otherwise.",
    ),
    spec(
        "smembers",
        2,
        &["readonly"],
        1,
        1,
        1,
        "set",
        "Returns all members of the set.",
    ),
    spec(
        "smismember",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "set",
        "Returns an array of 1/0 values for each member, indicating existence.",
    ),
    spec(
        "smove",
        4,
        &["write", "fast"],
        1,
        2,
        1,
        "set",
        "Atomically moves a member from one set to another.",
    ),
    spec(
        "spop",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "set",
        "Removes and returns one or more random members from the set.",
    ),
    spec(
        "srandmember",
        -2,
        &["readonly"],
        1,
        1,
        1,
        "set",
        "Returns one or more random members without removing them.",
    ),
    spec(
        "srem",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "set",
        "Removes one or more members from a set.",
    ),
    spec(
        "sscan",
        -3,
        &["readonly"],
        1,
        1,
        1,
        "set",
        "Iterates a set incrementally: returns the next cursor plus at most COUNT members (default 10).",
    ),
    spec(
        "strlen",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "strings",
        "Returns the length of the string stored at key.",
    ),
    spec(
        "subscribe",
        -2,
        &["pubsub", "noscript", "loading", "stale"],
        0,
        0,
        0,
        "pub/sub",
        "Subscribes the client to one or more channels.",
    ),
    spec(
        "sunion",
        -2,
        &["readonly"],
        1,
        -1,
        1,
        "set",
        "Returns the union of all given sets.",
    ),
    spec(
        "sunionstore",
        -3,
        &["write", "denyoom"],
        1,
        -1,
        1,
        "set",
        "Stores the union into destination and returns its size.",
    ),
    spec(
        "ttl",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "expiry",
        "Returns the remaining time-to-live of a key in seconds.",
    ),
    spec(
        "type",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "keys",
        "Returns the type of the value stored at key: string, hash, list, set, zset, ratelimit, or none if the key does not exist.",
    ),
    spec(
        "unlink",
        -2,
        &["write", "fast"],
        1,
        -1,
        1,
        "keys",
        "Non-blocking delete.",
    ),
    spec(
        "unsubscribe",
        -1,
        &["pubsub", "noscript", "loading", "stale"],
        0,
        0,
        0,
        "pub/sub",
        "Unsubscribes from the given channels.",
    ),
    spec(
        "unwatch",
        1,
        &["noscript", "loading", "stale", "fast", "allow_busy"],
        0,
        0,
        0,
        "observable keys",
        "Stops watching the given keys.",
    ),
    spec(
        "watch",
        -2,
        &["noscript", "loading", "stale", "fast", "allow_busy"],
        1,
        -1,
        1,
        "observable keys",
        "Marks the given key(s) for optimistic locking, and (over WebSocket) registers the connection for keychange push notifications.",
    ),
    spec(
        "zadd",
        -4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Adds members with scores.",
    ),
    spec(
        "zcard",
        2,
        &["readonly", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Returns the number of members in the sorted set.",
    ),
    spec(
        "zcount",
        4,
        &["readonly", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Returns the number of members with scores between min and max.",
    ),
    spec(
        "zincrby",
        4,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Adds increment to the score of member.",
    ),
    spec(
        "zmscore",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Returns the scores of multiple members.",
    ),
    spec(
        "zrange",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "sorted set",
        "Returns members between rank start and stop (0-based, ascending).",
    ),
    spec(
        "zrangebyscore",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "sorted set",
        "Returns members with scores between min and max.",
    ),
    spec(
        "zrank",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Returns the 0-based rank of a member in ascending score order.",
    ),
    spec(
        "zrem",
        -3,
        &["write", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Removes members from the sorted set.",
    ),
    spec(
        "zrevrange",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "sorted set",
        "Same as ZRANGE, but returns members in descending score order.",
    ),
    spec(
        "zrevrangebyscore",
        -4,
        &["readonly"],
        1,
        1,
        1,
        "sorted set",
        "Same, but from high score to low.",
    ),
    spec(
        "zrevrank",
        -3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Returns the rank in descending score order.",
    ),
    spec(
        "zscan",
        -3,
        &["readonly"],
        1,
        1,
        1,
        "sorted set",
        "Iterates a sorted set incrementally: returns the next cursor plus at most COUNT member, score pairs (default 10).",
    ),
    spec(
        "zscore",
        3,
        &["readonly", "fast"],
        1,
        1,
        1,
        "sorted set",
        "Returns the score of a member, or nil if the member does not exist.",
    ),
    // ── Handshake and introspection ───────────────────────────────────────
    spec(
        "quit",
        -1,
        &[
            "noscript",
            "loading",
            "stale",
            "fast",
            "no_auth",
            "allow_busy",
        ],
        0,
        0,
        0,
        "core",
        "Closes the connection after replying OK.",
    ),
    spec(
        "client",
        -2,
        &["noscript", "loading", "stale"],
        0,
        0,
        0,
        "core",
        "Connection introspection and push settings: ID, INFO, LIST, GETNAME, SETNAME, SETINFO, DELTA.",
    ),
    spec(
        "config",
        -2,
        &["admin", "noscript", "loading", "stale"],
        0,
        0,
        0,
        "core",
        "Reads server configuration. Recached's configuration is start-time only, so CONFIG SET is refused.",
    ),
    spec(
        "command",
        -1,
        &["loading", "stale"],
        0,
        0,
        0,
        "core",
        "Reports the command catalog: COUNT, LIST, INFO and DOCS.",
    ),
    // Container rows carry the key positions Redis reports for the container
    // itself, which are 0/0/0 even for `MEMORY`, whose `USAGE` subcommand does
    // take a key at position 2. Redis publishes that through the subcommand
    // tree, which Recached does not implement; copying the container row keeps
    // a proxy reading the same numbers here as from the server it was built
    // against, and Recached has no shards to route to in any case.
    spec(
        "cluster",
        -2,
        &["stale"],
        0,
        0,
        0,
        "core",
        "Cluster topology. Recached is standalone: the container is refused, and INFO reports cluster_enabled:0.",
    ),
    spec(
        "memory",
        -2,
        &["readonly"],
        0,
        0,
        0,
        "keys",
        "MEMORY USAGE reports the approximate bytes one key holds. The allocator subcommands are refused.",
    ),
    spec(
        "module",
        -2,
        &["admin", "noscript"],
        0,
        0,
        0,
        "core",
        "Lists loaded modules. Recached has no module API, so the list is always empty.",
    ),
    spec(
        "pubsub",
        -2,
        &["pubsub", "loading", "stale"],
        0,
        0,
        0,
        "pub/sub",
        "Introspects the pub/sub system: CHANNELS, NUMSUB and NUMPAT.",
    ),
    // ── Recached-only ─────────────────────────────────────────────────────
    // No Redis counterpart, so these rows are declared rather than transcribed.
    spec(
        "eset",
        3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "strings",
        "Ephemeral set: stores a string whose lifetime is bound to the connection that wrote it.",
    ),
    spec(
        "eadd",
        -3,
        &["write", "denyoom", "fast"],
        1,
        1,
        1,
        "set",
        "Ephemeral add: adds set members whose lifetime is bound to the connection that added them.",
    ),
    spec(
        "jset",
        4,
        &["write", "denyoom"],
        1,
        1,
        1,
        "json",
        "Sets JSON at a path ($ is the whole document).",
    ),
    spec(
        "jget",
        -2,
        &["readonly"],
        1,
        1,
        1,
        "json",
        "Reads JSON at a path, serialized. Defaults to $.",
    ),
    spec(
        "jmerge",
        3,
        &["write", "denyoom"],
        1,
        1,
        1,
        "json",
        "Applies an RFC 7386 JSON Merge Patch to the whole document.",
    ),
    spec(
        "rlset",
        4,
        &["write", "fast"],
        1,
        1,
        1,
        "rate limiting",
        "Configures a sliding-window rate limiter on a key.",
    ),
    spec(
        "rlcheck",
        -2,
        &["write", "fast"],
        1,
        1,
        1,
        "rate limiting",
        "Records an attempt and reports [allowed, remaining, retry_after_ms].",
    ),
    // Not Redis's replication SYNC, which shares the name and nothing else.
    spec(
        "sync",
        -1,
        &["noscript", "loading", "stale"],
        0,
        0,
        0,
        "sync scoping",
        "Sets this WebSocket connection's sync scopes, or reports them when called with no arguments.",
    ),
    spec(
        "dedup",
        -4,
        &["write", "noscript"],
        0,
        0,
        0,
        "sync scoping",
        "Wraps a write with a per-client monotonic id so an offline replay is skipped.",
    ),
    spec(
        "qsub",
        2,
        &["pubsub", "noscript"],
        0,
        0,
        0,
        "live queries",
        "Subscribes to a live query: current state of every matching key, then keychange pushes.",
    ),
    spec(
        "qunsub",
        -1,
        &["pubsub", "noscript"],
        0,
        0,
        0,
        "live queries",
        "Drops one live query, or all of them without an argument.",
    ),
];

/// Look a command up by name, case-insensitively. Returns `None` for anything
/// the parser would answer `unknown command` to.
pub fn lookup(name: &str) -> Option<&'static CommandSpec> {
    CATALOG.iter().find(|c| c.name.eq_ignore_ascii_case(name))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cmd::Command;
    use crate::resp::Value;

    /// Every catalog row must name a command the parser actually accepts.
    ///
    /// The reverse direction — every command the parser accepts has a row — is
    /// checked in the server by `every_command_is_in_the_catalog`, which walks
    /// the exhaustive `Command` variant table. Together they close the loop: a
    /// command cannot be added, removed or renamed without one of them failing.
    #[test]
    fn catalog_names_are_real_commands() {
        for spec in CATALOG {
            let frame = Value::Array(Some(vec![Value::BulkString(Some(
                spec.name.as_bytes().to_vec(),
            ))]));
            // Parsing bare `NAME` either succeeds or fails on arity; what it
            // must never do is fall through to Unknown, which is what the
            // server answers `unknown command` to.
            if let Ok(Command::Unknown(_)) = Command::from_value(frame) {
                panic!(
                    "catalog lists '{}', which the parser does not know",
                    spec.name
                );
            }
        }
    }

    #[test]
    fn catalog_has_no_duplicate_names() {
        let mut names: Vec<&str> = CATALOG.iter().map(|c| c.name).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(before, names.len(), "a command is listed twice");
    }

    #[test]
    fn catalog_names_are_lowercase() {
        // Redis reports lowercase names, and clients index the COMMAND DOCS
        // map by exactly the string they get back.
        for spec in CATALOG {
            assert_eq!(spec.name, spec.name.to_lowercase(), "{}", spec.name);
        }
    }

    #[test]
    fn every_command_has_a_summary() {
        for spec in CATALOG {
            assert!(
                !spec.summary.is_empty(),
                "{} has no summary, so COMMAND DOCS would describe it as nothing",
                spec.name
            );
            assert!(!spec.group.is_empty(), "{} has no group", spec.name);
        }
    }

    #[test]
    fn key_positions_agree_with_arity() {
        for spec in CATALOG {
            if spec.first_key == 0 {
                assert_eq!(
                    spec.step, 0,
                    "{} claims no keys but a non-zero step",
                    spec.name
                );
                continue;
            }
            assert!(spec.step >= 1, "{} has keys but no stride", spec.name);
            // A command whose first key sits at position N needs at least N+1
            // arguments including its own name.
            let min_args = spec.arity.abs();
            assert!(
                min_args > spec.first_key,
                "{}: first key at {} but arity is {}",
                spec.name,
                spec.first_key,
                spec.arity
            );
        }
    }

    #[test]
    fn lookup_is_case_insensitive() {
        assert_eq!(lookup("GET").map(|c| c.name), Some("get"));
        assert_eq!(lookup("HsCaN").map(|c| c.name), Some("hscan"));
        assert!(lookup("nosuchcommand").is_none());
    }
}
